export const en = {
  logo: 'Notes',
  greeting: 'Hello!',
  username: 'username',
  password: 'password',
  submit: 'Submit',
  readMore: 'more',
  newNote: 'New note',
  public: 'Public',
  private: 'Private',
  favorite: 'favorite',
  cancel: 'Cancel',
  confirm: 'Confirm',
  deleteMessage: 'Are you sure you want to delete this note?',
  errorLogin: 'Invalid username or password!',
  errorInvalid: 'Invalid input!',
  errorTags: 'Please check the format!',
  tagsFormat: 'tags in format: tag, tag, tag',
  title: 'title',
  text: 'text',
  errorPageHeader: 'Oops!',
  errorPageMessage: 'Sorry, an unexpected error has occurred.',
  newPassword: 'new password',
  changePasswordScreen: 'Change password',
  errorPassword:
    'Valid format: 8 symbols, including at least 1 letter, 1 digit and 1 special character',
  changedPasswordMessage: 'Password was successfully changed!',
  noteWasCreated: 'Note was created!',
  noteWasDeleted: 'Note was deleted!',
  errorNote: 'Something went wrong!',
}
