export const en = {
  logo: 'Notes',
  greeting: 'Hello!',
  username: 'username',
  password: 'password',
  submit: 'Submit',
  readMore: 'more',
  newNote: 'New note',
  public: 'Public',
  private: 'Private',
  cancel: 'Cancel',
  confirm: 'Confirm',
  deleteMessage: 'Are you sure you want to delete this note?',
  errorInvalid: 'Invalid username or password!',
  errorTags: 'Please check the format!',
  tagsFormat: 'tags in format: tag, tag, tag',
  title: 'title',
  text: 'text',
}
