export const ru = {
  logo: 'Заметки',
  greeting: 'Привет!',
  username: 'имя пользователя',
  password: 'пароль',
  submit: 'Отправить',
  readMore: 'больше',
  newNote: 'Новая заметка',
  public: 'Общие',
  private: 'Личные',
  cancel: 'Отменить',
  confirm: 'Подтвердить',
  deleteMessage: 'Вы уверены, что хотите удалить заметку?',
  errorInvalid: 'Неверное имя пользователя или пароль!',
  errorTags: 'Проверьте, пожалуйста, формат!',
  tagsFormat: 'Теги в формате: тег, тег, тег',
  title: 'заголовок',
  text: 'текст',
}
