export const ru = {
  logo: 'Заметки',
  greeting: 'Привет!',
  username: 'имя пользователя',
  password: 'пароль',
  submit: 'Отправить',
  readMore: 'больше',
  newNote: 'Новая заметка',
  public: 'Общие',
  private: 'Личные',
  favorite: 'избранные',
  cancel: 'Отменить',
  confirm: 'Подтвердить',
  deleteMessage: 'Вы уверены, что хотите удалить заметку?',
  errorLogin: 'Неверное имя пользователя или пароль!',
  errorInvalid: 'Неправильный формат ввода!',
  errorTags: 'Проверьте, пожалуйста, формат!',
  tagsFormat: 'Теги в формате: тег, тег, тег',
  title: 'заголовок',
  text: 'текст',
  errorPageHeader: 'Упс!',
  errorPageMessage: 'Извините, произошла непредвиденная ошибка.',
  newPassword: 'новый пароль',
  changePasswordScreen: 'Изменить пароль',
  errorPassword:
    'Валидный формат: 8 символов, включая хотя бы 1 букву, 1 цифру и 1 специальный символ',
  changedPasswordMessage: 'Пароль был успешно изменен!',
  noteWasCreated: 'Заметка создана!',
  noteWasDeleted: 'Заметка удалена!',
  errorNote: 'Что-то пошло не так!',
}
